trigger:
  - main

parameters:
  - name: microserviceName
    displayName: 'Microservice Name'
    type: string
    default: 'placeholder'

  - name: suiteFileName
    displayName: 'Suite XML File Name'
    type: string
    default: 'placeholder.xml'

pool:
  vmImage: 'windows-latest'

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '21'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    continueOnError: true
    inputs:
      mavenPomFile: 'automation/pom.xml'
      goals: 'clean test'
      options: >
        -DsuiteXmlFile=testng/${{ parameters.microserviceName }}/${{ parameters.suiteFileName }}
        -pl webapi-testng 
        -am
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '1.21' # Will be overridden in JavaToolInstaller
      mavenVersionOption: 'Default'
      mavenAuthenticateFeed: false
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'Maven Tests'
